
--CAPTURE PT MULTIPLE RACES AND ETHNICITY BY JOINING TABLES
/*******************-----------Preparing Ethnicity Cohorts----------******************/

IF OBJECT_ID('TEMPDB..#EHISP') IS NOT NULL DROP TABLE #EHISP;
SELECT *
       ,'HISPANIC' AS ETH_GROUP 
INTO #EHISP
FROM DCPWDBS149.Clarity_Rpt_Crystal.dbo.ZC_ETHNIC_GROUP
WHERE (NAME LIKE ('%HISPANIC%') 
            AND NAME NOT LIKE ('%NON%')) 
      OR NAME LIKE ('%MEXIC%') 
	  OR NAME LIKE ('%CUBAN%') 
	  OR NAME LIKE ('%PUERT%')





IF OBJECT_ID('TEMPDB..#ENON_HISP') IS NOT NULL DROP TABLE #ENON_HISP;
SELECT *
       ,'NON_HISPANIC' AS ETH_GROUP 
INTO #ENON_HISP
FROM DCPWDBS149.Clarity_Rpt_Crystal.dbo.ZC_ETHNIC_GROUP
WHERE (NAME LIKE ('%HISPANIC%') AND NAME LIKE ('%NON%')) 
      OR NAME IN ('WHITE', 'BLACK', 'NATIVE AMERICAN', 'ASIAN OR PACIFIC ISLANDER', 
	               'WHITE/UNKNOWN','BLACK OR AFRICAN AMERICAN/UNKNOWN', 
	              'AMERICAN INDIAN OR ALASKA NATIVE/UNKNOWN', 'ASIAN/UNKNOWN', 'RUSSIAN', 
				   'UKRAINIAN', 'FRENCH', 'GERMAN', 'JAPANESE',
				   'NATIVE HAWAIIAN OR PACIFIC ISLANDER/UNKNOWN', 'FILIPINO') 




/*grouping all patients' ethnicity--generalize*/
IF OBJECT_ID('TEMPDB..#E_HISP_NONHISP ') IS NOT NULL DROP TABLE #E_HISP_NONHISP;
SELECT * 
INTO #E_HISP_NONHISP 
FROM 
(SELECT * FROM #EHISP 
	UNION ALL
 SELECT * FROM #ENON_HISP) AS AllEthnicity




IF OBJECT_ID('TEMPDB..#EOTHER') IS NOT NULL DROP TABLE #EOTHER;
SELECT *
       , 'OTHER' AS ETH_GROUP 
INTO #EOTHER
FROM DCPWDBS149.Clarity_Rpt_Crystal.dbo.ZC_ETHNIC_GROUP
WHERE ETHNIC_GROUP_C NOT IN (SELECT ETHNIC_GROUP_C FROM #E_HISP_NONHISP)



--combine tables all ethnicity including ethinicity and others.  
IF OBJECT_ID('TEMPDB..#EALLETHNICITY') IS NOT NULL DROP TABLE #EALLETHNICITY;
SELECT DISTINCT * 
INTO #EALLETHNICITY 
FROM 
    (SELECT * FROM #E_HISP_NONHISP UNION ALL
     SELECT * FROM #EOTHER) AS A



---------------------------------------------------------------------------------------------------------------------------------------------
/*ADDING ETHNICITY TO THE COHORT PATIENTS*/
IF OBJECT_ID('TEMPDB..#COHORT_PLUS_ETHNICITY') IS NOT NULL DROP TABLE #COHORT_PLUS_ETHNICITY;
SELECT COHORT.*
       , CAST(PT.BIRTH_DATE AS DATE) AS DOB
	   ,SEX.NAME AS GENDER
       ,ETHNIC.NAME AS ETHNICITY_NAME
	   ,ETHNIC.ETH_GROUP AS ETHNIC_GROUP 
INTO #COHORT_PLUS_ETHNICITY
FROM #BIOBANK_BASE AS COHORT                                 ------------this is the talbe we can add more patient information
     LEFT JOIN DCPWDBS149.Clarity_Rpt_Crystal.dbo.PATIENT AS PT ON PT.PAT_ID = COHORT.PAT_ID
	 LEFT JOIN DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.ZC_SEX  AS SEX ON SEX.RCPT_MEM_SEX_C = PT.SEX_C
     LEFT JOIN #EALLETHNICITY                             AS ETHNIC ON ETHNIC.ETHNIC_GROUP_C=PT.ETHNIC_GROUP_C 






----------------------------------------------------------------------------------------------------------------------------------------
/**********------------------PREPARE RACES----------------------***********/
IF OBJECT_ID('TEMPDB..#RWHITE ') IS NOT NULL DROP TABLE #RWHITE;
SELECT DISTINCT *
       ,'WHITE' AS RACE_CATEGORY                    --group1 is a flag variable
INTO #RWHITE 
FROM DCPWDBS149.Clarity_Rpt_Crystal.dbo.ZC_PATIENT_RACE
WHERE NAME LIKE ('%WHITE%') 




IF OBJECT_ID('TEMPDB..#RBLACK  ') IS NOT NULL DROP TABLE #RBLACK;
SELECT DISTINCT *
       ,'BLACK OR AFRICAN AMERICAN' AS RACE_CATEGORY 
INTO #RBLACK 
FROM DCPWDBS149.Clarity_Rpt_Crystal.dbo.ZC_PATIENT_RACE
WHERE NAME LIKE ('%BLACK%') 




IF OBJECT_ID('TEMPDB..#RNATIVEINDIAN') IS NOT NULL DROP TABLE #RNATIVEINDIAN;
SELECT DISTINCT *
       ,'AMERICAN INDIAN/ALASKA NATIVE' AS RACE_CATEGORY 
INTO #RNATIVEINDIAN 
FROM DCPWDBS149.Clarity_Rpt_Crystal.dbo.ZC_PATIENT_RACE
WHERE NAME LIKE ('%ALASKA%')




IF OBJECT_ID('TEMPDB..#RHAWAIIN ') IS NOT NULL DROP TABLE #RHAWAIIN ;
SELECT *
       , 'NATIVE HAWAIIAN/PACIFIC ISLANDER' AS RACE_CATEGORY 
INTO #RHAWAIIN 
FROM DCPWDBS149.Clarity_Rpt_Crystal.dbo.ZC_PATIENT_RACE
WHERE NAME LIKE ('%PACIFIC%') 
      OR NAME LIKE ('%ISLAND%') 
	  OR NAME LIKE ('%HAWAII%') 
	  OR NAME LIKE ('%GUAMANIA%') 
	  OR NAME LIKE ('%CHAMARRO%') 
	  OR NAME LIKE ('%SAMOA%')




IF OBJECT_ID('TEMPDB..#RASIAN') IS NOT NULL DROP TABLE #RASIAN;
SELECT *
      ,'ASIAN' AS RACE_CATEGORY 
INTO #RASIAN 
FROM DCPWDBS149.Clarity_Rpt_Crystal.dbo.ZC_PATIENT_RACE
WHERE NAME LIKE ('%ASIAN INDIAN%') 
      OR NAME LIKE ('%BANGLADESH%') 
	  OR NAME LIKE ('%BHUTAN%') 
	  OR NAME LIKE ('%BURMESE%') 
	  OR NAME LIKE ('%CAMBODIAN%') 
	  OR NAME LIKE ('%CHINESE%') 
	  OR NAME LIKE ('%TAIWAN%') 
	  OR NAME LIKE ('%FILIPINO%') 
	  OR NAME LIKE ('%HMONG%') 
	  OR NAME LIKE ('%INDONESIA%') 
	  OR NAME LIKE ('%IWO%') 
	  OR NAME LIKE ('%JAPAN%') 
	  OR NAME LIKE ('%KOREA%') 
	  OR NAME LIKE ('%LAOTIAN%') 
	  OR NAME LIKE ('%MALAYSIA%') 
	  OR NAME LIKE ('%MALDIV%') 
	  OR NAME LIKE ('%MONGOLIA%') 
	  OR NAME LIKE ('%NEPALESE%') 
	  OR NAME LIKE ('%OKINAWA%') 
	  OR NAME LIKE ('%PAKISTAN%') 
	  OR NAME LIKE ('%SINGAPORE%') 
	  OR NAME LIKE ('%SRI%') 
	  OR NAME LIKE ('%THAI%') 
	  OR NAME LIKE ('%VIETNAM%') 
	  OR (NAME LIKE ('%ASIA%') 
	  AND NAME NOT LIKE ('%CAUC%'))




IF OBJECT_ID('TEMPDB..#R_5GROUPS') IS NOT NULL DROP TABLE #R_5GROUPS;
SELECT * 
INTO #R_5GROUPS 
FROM 
(SELECT * FROM #RWHITE 
	UNION ALL
 SELECT * FROM #RBLACK 
	UNION ALL
 SELECT * FROM #RNATIVEINDIAN 
	UNION ALL
 SELECT * FROM #RHAWAIIN 
	UNION ALL
 SELECT * FROM #RASIAN) AS GroupRaces





IF OBJECT_ID('TEMPDB..#ROTHER') IS NOT NULL DROP TABLE #ROTHER;
SELECT *
       , 'OTHER' AS RACE_CATEGORY
INTO #ROTHER 
FROM DCPWDBS149.Clarity_Rpt_Crystal.dbo.ZC_PATIENT_RACE
WHERE PATIENT_RACE_C NOT IN (SELECT PATIENT_RACE_C FROM #R_5GROUPS)




/*#RALLRACES IS THE MASTER TABLE OF RACES----generalize*/----use this
IF OBJECT_ID('TEMPDB..#RALLRACES') IS NOT NULL DROP TABLE #RALLRACES;
SELECT * 
INTO #RALLRACES 
FROM 
(SELECT * FROM #R_5GROUPS 
	UNION ALL
 SELECT * FROM #ROTHER) AS ALLRaces

 --select * from #RALLRACES


 



 /*START FROM HERE, GROUPING PATIENTS WITH/WITHOUT MULTIPLE RACES*/------------------------------------
 --------All RACE & MULTI-RACE
IF OBJECT_ID('TEMPDB..#RACE_MULTI_RACE') IS NOT NULL DROP TABLE #RACE_MULTI_RACE;
SELECT DISTINCT AL.PAT_ID
       , R.NAME
	   , R.RACE_CATEGORY
INTO #RACE_MULTI_RACE
FROM #COHORT_PLUS_ETHNICITY AS AL 
     LEFT JOIN DCPWDBS149.Clarity_Rpt_Crystal.dbo.PATIENT_RACE AS PR ON PR.PAT_ID = AL.PAT_ID
     LEFT JOIN #RALLRACES   AS R  ON R.PATIENT_RACE_C = PR.PATIENT_RACE_C   


-----SINGLE OUT PT WITH MULTIPLE RACES, one pt can have two to three races
IF OBJECT_ID('TEMPDB..#MULTI_RACE') IS NOT NULL DROP TABLE #MULTI_RACE;
SELECT DISTINCT PAT_ID 
INTO #MULTI_RACE
FROM #RACE_MULTI_RACE
GROUP BY PAT_ID HAVING COUNT(DISTINCT RACE_CATEGORY)>= 2   


------SINGLE OUT PT WITH SINGE RACE, who don't have multiple races
IF OBJECT_ID('TEMPDB..#ONE_RACE') IS NOT NULL DROP TABLE #ONE_RACE;
SELECT DISTINCT * 
INTO #ONE_RACE
FROM #RACE_MULTI_RACE
WHERE PAT_ID NOT IN (SELECT PAT_ID FROM #MULTI_RACE) ORDER BY PAT_ID   




IF OBJECT_ID('TEMPDB..#MULTI_RACE2') IS NOT NULL DROP TABLE #MULTI_RACE2;
SELECT DISTINCT AL2.PAT_ID
       , AL1.NAME 
	   , 'MULTI-RACE' AS RACE_CATEGORY   --a flag variable
INTO #MULTI_RACE2
FROM #MULTI_RACE                 AS AL2 
     INNER JOIN #RACE_MULTI_RACE AS AL1 ON AL1.PAT_ID=AL2.PAT_ID   



/*this is the final table of all the distinct pt with races and group */
IF OBJECT_ID('TEMPDB..#AL_RACE') IS NOT NULL DROP TABLE #AL_RACE;
SELECT DISTINCT *
INTO #AL_RACE
FROM
(SELECT * FROM #ONE_RACE
	UNION ALL
 SELECT * FROM #MULTI_RACE2) AS A    




  
/*ADDING RACE TO THE COHORT (HAVING AGE, GENDER, ETHNICITY AND RACE READY)*/
---THIS IS THE BASE TABLE!!!!!!!!!!!!!!!!!!!!!!!!!!
IF OBJECT_ID('TEMPDB..#COHORT_DEMO') IS NOT NULL DROP TABLE #COHORT_DEMO;
SELECT COHORT.*
       , RACE.NAME AS RACE_NAME
	   , RACE.RACE_CATEGORY
INTO #COHORT_DEMO
FROM #COHORT_PLUS_ETHNICITY AS COHORT 
     LEFT JOIN #AL_RACE AS RACE ON RACE.PAT_ID = COHORT.PAT_ID
