/********************************************************************************
Program name:	UTIL_TYPOL_DATA_EXTRACT.sql
Purpose:		Extract ED visits and inpatient admissions at ABSMC in 2014.
Project name:	GIS East Bay
Investigators:	Alice Pressman
Author:			Anjali Franco
Date created:	02-19-15
Input data:		DCPWDBS149.Clarity_Rpt_Crystal.dbo.HSP_ACCOUNT
				DCPWDBS149.Clarity_Rpt_Crystal.dbo.CLARITY_LOC	
Output data:	DCQWDBS088.GIS.dbo.UTIL_TYPOL_ED_VISITS_2014
				DCQWDBS088.GIS.dbo.UTIL_TYPOL_ED_VISITS_2015Q1Q2
				DCQWDBS088.GIS.dbo.UTIL_TYPOL_ED_VISITS_2015Q1Q2Q3
				DCQWDBS088.GIS.dbo.UTIL_TYPOL_ED_VISITS_2015
				DCQWDBS088.GIS.dbo.UTIL_TYPOL_IP_ADMITS_2014
				DCQWDBS088.GIS.dbo.UTIL_TYPOL_IP_ADMITS_2015Q1Q2
				DCQWDBS088.GIS.dbo.UTIL_TYPOL_IP_ADMITS_2015Q1Q2Q3
				DCQWDBS088.GIS.dbo.UTIL_TYPOL_IP_ADMITS_2015
				DCQWDBS088.GIS.dbo.UTIL_TYPOL_ASHBY_PATIENTS
				DCQWDBS088.GIS.dbo.UTIL_TYPOL_SUMMIT_PATIENTS
				DCQWDBS088.GIS.dbo.UTIL_TYPOL_ASHBY_PATIENTS_NAMES
				DCQWDBS088.GIS.dbo.UTIL_TYPOL_SUMMIT_PATIENTS_NAMES
Modifications:
Date		Description
--------	-----------
03-24-15	Extract patient information and demographics.  DID NOT RERUN CODE.
06-29-15	Run typology for Q1 and Q2 2015.
10-27-15	Run typology for Q1-Q3 2015.  Some hospital accounts could
			have been revised.
01-26-16	Run typology for 2015.  Some hospital accounts could
			have been revised.
********************************************************************************/

/*
--EXTRACT ED VISITS--
*/


USE CLARITY_RPT_CRYSTAL;


IF OBJECT_ID('tempdb..#UTIL_TYPOL_ED_VISITS_2016') IS NOT NULL DROP Table #UTIL_TYPOL_ED_VISITS_2016;

SELECT DISTINCT A.PAT_ID,
				A.HSP_ACCOUNT_ID,
				A.ADM_DATE_TIME,
				A.DISCH_DATE_TIME,
				DATEDIFF(dy, A.ADM_DATE_TIME, A.DISCH_DATE_TIME) AS ED_LOS_DAYS,  --*****updated
				B.LOC_NAME,
				C.NAME AS ADMISSION_SOURCE_C
		
INTO #UTIL_TYPOL_ED_VISITS_2016
FROM DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.HSP_ACCOUNT                  AS A
     INNER JOIN DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.CLARITY_LOC       AS B ON A.LOC_ID = B.LOC_ID
     LEFT JOIN DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.ZC_ADMISSION_SRC   AS C ON A.ADMISSION_SOURCE_C = C.ADMISSION_SRC_C
	 INNER JOIN DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.HSP_ACCT_DX_LIST  AS DX ON DX.HSP_ACCOUNT_ID = A.HSP_ACCOUNT_ID
	 INNER JOIN DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.CLARITY_EDG       AS EDG   ON EDG.DX_ID = DX.DX_ID
WHERE YEAR(A.ADM_DATE_TIME) = 2016
	  AND MONTH(A.ADM_DATE_TIME) IN (7, 8, 9)   --by different quarters
	  AND A.ACCT_BASECLS_HA_C = '3'             --emergency admission
	  AND B.LOC_NAME IN ('ALTA BATES SUMMIT - ALTA BATES', 'ALTA BATES SUMMIT - MERRITT')
      AND EDG.CURRENT_ICD10_LIST NOT LIKE 'C%'
		     AND EDG.CURRENT_ICD10_LIST NOT LIKE 'D0%' 
			 AND  EDG.CURRENT_ICD10_LIST NOT LIKE 'D37%' 
			 AND  EDG.CURRENT_ICD10_LIST NOT LIKE 'D38%' 
			 AND  EDG.CURRENT_ICD10_LIST NOT LIKE 'D39%' 
			 AND  EDG.CURRENT_ICD10_LIST NOT LIKE 'D4%'
			 AND EDG.CURRENT_ICD10_LIST NOT LIKE 'O%'
			 AND EDG.CURRENT_ICD10_LIST NOT LIKE 'Z3%'
			 AND EDG.CURRENT_ICD10_LIST NOT LIKE 'Z23%'
			 AND EDG.CURRENT_ICD10_LIST NOT LIKE 'Z85.05%'
			 AND EDG.CURRENT_ICD10_LIST NOT LIKE 'Z51.11%'
			 AND EDG.CURRENT_ICD10_LIST NOT LIKE 'P08.21%'
			AND EDG.CURRENT_ICD10_LIST NOT LIKE 'Z92.21%'	


--select * from #UTIL_TYPOL_ED_VISITS_2016                             --total 19,986 after exclusion 118,960
--select count(distinct pat_id) from #UTIL_TYPOL_ED_VISITS_2016        --14905


--*******************************************************************************************************************
--EXTRACT INPATIENT ADMISSIONS--

IF OBJECT_ID('tempdb..#UTIL_TYPOL_IP_ADMITS_2016') IS NOT NULL DROP Table #UTIL_TYPOL_IP_ADMITS_2016;

SELECT DISTINCT A.PAT_ID,
				A.HSP_ACCOUNT_ID,
				A.ADM_DATE_TIME,
				A.DISCH_DATE_TIME,
				B.LOC_NAME 
			--	, DRG.DRG_NAME  
			--	, EDG.DX_NAME
			--	,EDG.CURRENT_ICD10_LIST
			    ,DATEDIFF(dy, A.ADM_DATE_TIME, A.DISCH_DATE_TIME) AS IP_LOS_DAYS ---******updated
				, A.BILL_DRG_GMLOS AS DRG_GEOMETRIC_MEAN_LOS			
				, (DATEDIFF(dy, A.ADM_DATE_TIME, A.DISCH_DATE_TIME) -  CONVERT(NUMERIC(10, 2), A.BILL_DRG_GMLOS)) AS DRG_EXCESS_GEOMETRIC_MEAN
				, A.TOT_CHGS
				,CASE 
				     WHEN DATEDIFF(dy, A.ADM_DATE_TIME, A.DISCH_DATE_TIME) = 0 THEN NULL
					 WHEN DATEDIFF(dy, A.ADM_DATE_TIME, A.DISCH_DATE_TIME) !=0 THEN CONVERT(NUMERIC(10, 3), ((A.TOT_CHGS/DATEDIFF(dy, A.ADM_DATE_TIME, A.DISCH_DATE_TIME))  * (DATEDIFF(dy, A.ADM_DATE_TIME, A.DISCH_DATE_TIME) -  CONVERT(NUMERIC(10, 2), A.BILL_DRG_GMLOS))))
				 END AS PAY_EXCESS_AVG_LOS_G_MEAN

INTO #UTIL_TYPOL_IP_ADMITS_2016
FROM DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.HSP_ACCOUNT AS A
     INNER JOIN DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.CLARITY_LOC AS B ON A.LOC_ID = B.LOC_ID
	 INNER JOIN DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.HSP_ACCT_DX_LIST  AS DX ON DX.HSP_ACCOUNT_ID = A.HSP_ACCOUNT_ID
	 INNER JOIN DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.CLARITY_EDG       AS EDG   ON EDG.DX_ID = DX.DX_ID
	 LEFT JOIN DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.CLARITY_DRG AS DRG ON DRG.DRG_ID = A.FINAL_DRG_ID
WHERE YEAR(A.ADM_DATE_TIME) = 2016 		
        AND MONTH(A.ADM_DATE_TIME) IN (7, 8, 9)
		AND A.ACCT_BASECLS_HA_C = '1'  --hospital admission inpatients
		AND B.LOC_NAME IN ('ALTA BATES SUMMIT - ALTA BATES', 'ALTA BATES SUMMIT - MERRITT')
		AND  EDG.CURRENT_ICD10_LIST NOT LIKE 'C%'
		AND  EDG.CURRENT_ICD10_LIST NOT LIKE 'D0%' 
		AND  EDG.CURRENT_ICD10_LIST NOT LIKE 'D37%' 
		AND  EDG.CURRENT_ICD10_LIST NOT LIKE 'D38%' 
		AND  EDG.CURRENT_ICD10_LIST NOT LIKE 'D39%' 
		AND  EDG.CURRENT_ICD10_LIST NOT LIKE 'D4%'
		AND EDG.CURRENT_ICD10_LIST NOT LIKE 'O%'
		AND EDG.CURRENT_ICD10_LIST NOT LIKE 'Z3%'
        AND EDG.CURRENT_ICD10_LIST NOT LIKE 'Z23%'
		AND EDG.CURRENT_ICD10_LIST NOT LIKE 'Z85.05%'
		AND EDG.CURRENT_ICD10_LIST NOT LIKE 'Z51.11%'
		AND EDG.CURRENT_ICD10_LIST NOT LIKE 'P08.21%'
		AND EDG.CURRENT_ICD10_LIST NOT LIKE 'Z92.21%'	
--ORDER BY DX_NAME	
               /*
				,EDG.REF_BILL_CODE
			    , A.BILL_DRG_AMLOS AS DRG_ARITHMETRIC_MEAN_LOS
				, (DATEDIFF(dy, A.ADM_DATE_TIME, A.DISCH_DATE_TIME) - CONVERT(NUMERIC(10, 2), A.BILL_DRG_AMLOS)) AS DRG_EXCESS_ARITHMETRIC_MEAN
				,CASE 
				     WHEN DATEDIFF(dy, A.ADM_DATE_TIME, A.DISCH_DATE_TIME) = 0 THEN NULL
					 WHEN DATEDIFF(dy, A.ADM_DATE_TIME, A.DISCH_DATE_TIME) !=0 THEN CONVERT(NUMERIC(10, 3), ((A.TOT_CHGS/DATEDIFF(dy, A.ADM_DATE_TIME, A.DISCH_DATE_TIME)) * (DATEDIFF(dy, A.ADM_DATE_TIME, A.DISCH_DATE_TIME) - CONVERT(NUMERIC(10, 2), A.BILL_DRG_AMLOS))))
				 END AS PAY_EXCESS_AVG_LOS_A_MEAN
			*/
		/*
		AND  EDG.REF_BILL_CODE NOT LIKE 'C%'
		AND  EDG.REF_BILL_CODE NOT LIKE 'D0%' 
		AND  EDG.REF_BILL_CODE NOT LIKE 'D37%' 
		AND  EDG.REF_BILL_CODE NOT LIKE 'D38%' 
		AND  EDG.REF_BILL_CODE NOT LIKE 'D39%' 
		AND  EDG.REF_BILL_CODE NOT LIKE 'D4%'
		AND EDG.REF_BILL_CODE NOT LIKE 'O%'
		AND DRG.DRG_NAME NOT LIKE 'ABORTION%'
		AND DRG.DRG_NAME NOT LIKE 'CESAREAN SECTION%'
		AND DRG.DRG_NAME NOT LIKE 'CHEMO W ACUTE LEUKEMIA%'
		AND DRG.DRG_NAME NOT LIKE 'CHEMOTHERAPY W/O ACUTE%'
		AND DRG.DRG_NAME NOT LIKE 'ECTOPIC PREGNANCY%'
		AND DRG.DRG_NAME NOT LIKE 'FALSE LABOR%'
		AND DRG.DRG_NAME NOT LIKE 'LYMPHOMA & NON-ACUTE LEUKEMIA%'
		AND DRG.DRG_NAME NOT LIKE 'MALIGNANCY%'
		AND DRG.DRG_NAME NOT LIKE 'MASTECTOMY FOR%'
		AND DRG.DRG_NAME NOT LIKE 'OTHER ANTEPARTUM DIAGNOSES%'
		AND DRG.DRG_NAME NOT LIKE 'VAGINAL DELIVERY%'
		*/

			
			

--select * from #UTIL_TYPOL_IP_ADMITS_2016 ORDER BY DX_NAME --7689, 6961
--select count(distinct pat_id) from #UTIL_TYPOL_IP_ADMITS_2016  --6121
--select distinct ip_los_days, count(ip_los_days) from #UTIL_TYPOL_IP_ADMITS_2016 group by ip_los_days order by ip_los_days
--select distinct drg_name from #UTIL_TYPOL_IP_ADMITS_2016 order by drg_name





--***********************************************************************************************************
--ABSMC ASHBY CAMPUS TYPOLOGY
/*
select cnt_ed_ip_encs_grouped,
		COUNT(*) as cnt_patients_ashby
from #UTIL_TYPOL_ASHBY_PATIENTS
group by cnt_ed_ip_encs_grouped
order by cnt_ed_ip_encs_grouped


select * from #UTIL_TYPOL_ASHBY_PATIENTS where CNT_ED_IP_ENCS_GROUPED NOT IN (' 1: 0', ' 2-3: 0', ' 4-5: 0', ' 6-7: 0', ' 8-9: 0', '10+: 0'	)
(*/

IF OBJECT_ID('tempdb..#UTIL_TYPOL_ASHBY_PATIENTS') IS NOT NULL DROP Table #UTIL_TYPOL_ASHBY_PATIENTS;
SELECT PAT_ID, 
	   CASE WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 1'   AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 0')   THEN ' 1: 0'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 2-3' AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 0')   THEN ' 2-3: 0'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 4-5' AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 0')   THEN ' 4-5: 0'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 6-7' AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 0')   THEN ' 6-7: 0'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 8-9' AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 0')   THEN ' 8-9: 0'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = '10+'  AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 0')   THEN '10+: 0'	
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 0'   AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 1') THEN ' 0: 1'	
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 1'   AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 1') THEN ' 1: 1'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 2-3' AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 1') THEN ' 2-3: 1'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 4-5' AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 1') THEN ' 4-5: 1'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 6-7' AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 1') THEN ' 6-7: 1'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 8-9' AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 1') THEN ' 8-9: 1'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = '10+'  AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 1') THEN '10+: 1'	
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 0'   AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 2') THEN ' 0: 2'	
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 1'   AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 2') THEN ' 1: 2'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 2-3' AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 2') THEN ' 2-3: 2'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 4-5' AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 2') THEN ' 4-5: 2'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 6-7' AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 2') THEN ' 6-7: 2'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 8-9' AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 2') THEN ' 8-9: 2'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = '10+'  AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 2') THEN '10+: 2'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 0'   AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 3-4') THEN ' 0: 3-4'	
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 1'   AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 3-4') THEN ' 1: 3-4'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 2-3' AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 3-4') THEN ' 2-3: 3-4'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 4-5' AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 3-4') THEN ' 4-5: 3-4'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 6-7' AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 3-4') THEN ' 6-7: 3-4'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 8-9' AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 3-4') THEN ' 8-9: 3-4'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = '10+'  AND CNT_IP_ADMITS_ASHBY_GROUPED = ' 3-4') THEN '10+: 3-4'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 0'   AND CNT_IP_ADMITS_ASHBY_GROUPED = '5+') THEN ' 0:5+'	
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 1'   AND CNT_IP_ADMITS_ASHBY_GROUPED = '5+') THEN ' 1:5+'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 2-3' AND CNT_IP_ADMITS_ASHBY_GROUPED = '5+') THEN ' 2-3:5+'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 4-5' AND CNT_IP_ADMITS_ASHBY_GROUPED = '5+') THEN ' 4-5:5+'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 6-7' AND CNT_IP_ADMITS_ASHBY_GROUPED = '5+') THEN ' 6-7:5+'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = ' 8-9' AND CNT_IP_ADMITS_ASHBY_GROUPED = '5+') THEN ' 8-9:5+'
			WHEN (CNT_ED_VISITS_ASHBY_GROUPED = '10+'  AND CNT_IP_ADMITS_ASHBY_GROUPED = '5+') THEN '10+:5+'				
		END AS CNT_ED_IP_ENCS_GROUPED
	INTO #UTIL_TYPOL_ASHBY_PATIENTS
	FROM (
		SELECT PAT_ID, 
		   CASE WHEN CNT_ED_VISITS_ASHBY = 0 THEN ' 0'
				WHEN CNT_ED_VISITS_ASHBY IS NULL THEN ' 0'
				WHEN CNT_ED_VISITS_ASHBY = 1 THEN ' 1'
				WHEN CNT_ED_VISITS_ASHBY BETWEEN 2 AND 3 THEN ' 2-3'
				WHEN CNT_ED_VISITS_ASHBY BETWEEN 4 AND 5 THEN ' 4-5'
				WHEN CNT_ED_VISITS_ASHBY BETWEEN 6 AND 7 THEN ' 6-7'
				WHEN CNT_ED_VISITS_ASHBY BETWEEN 8 AND 9 THEN ' 8-9'
				WHEN CNT_ED_VISITS_ASHBY >= 10 THEN '10+'
			END AS CNT_ED_VISITS_ASHBY_GROUPED,
			CASE WHEN CNT_IP_ADMITS_ASHBY = 0 THEN ' 0'
				WHEN CNT_IP_ADMITS_ASHBY IS NULL THEN ' 0'
				WHEN CNT_IP_ADMITS_ASHBY = 1 THEN ' 1'
				WHEN CNT_IP_ADMITS_ASHBY = 2 THEN ' 2'
				WHEN CNT_IP_ADMITS_ASHBY BETWEEN 3 AND 4 THEN ' 3-4'
				WHEN CNT_IP_ADMITS_ASHBY >= 5 THEN '5+'
			END AS CNT_IP_ADMITS_ASHBY_GROUPED
		FROM (
			     SELECT CASE WHEN B.PAT_ID IS NULL THEN C.PAT_ID
						ELSE B.PAT_ID
					    END AS PAT_ID,
					    B.CNT_ED_VISITS_ASHBY,
					    C.CNT_IP_ADMITS_ASHBY
			      FROM (
					        SELECT PAT_ID,
							COUNT(*) AS CNT_ED_VISITS_ASHBY
					        FROM (
									SELECT * 
									FROM #UTIL_TYPOL_ED_VISITS_2016
									WHERE LOC_NAME = 'ALTA BATES SUMMIT - ALTA BATES'
								 ) AS A
					         GROUP BY A.PAT_ID
			            ) AS B
		FULL JOIN 
			(
					SELECT PAT_ID,
						   COUNT(*) AS CNT_IP_ADMITS_ASHBY
					FROM (
							SELECT * 
							FROM #UTIL_TYPOL_IP_ADMITS_2016
							WHERE LOC_NAME = 'ALTA BATES SUMMIT - ALTA BATES'
					     ) AS A
					GROUP BY A.PAT_ID
			) AS C
		ON B.PAT_ID = C.PAT_ID
		   ) AS D
	) AS E
/*) as f
group by f.cnt_ed_ip_encs_grouped*/




--**********************************************************************************************************************


select * from #UTIL_TYPOL_ASHBY_PATIENTS where CNT_ED_IP_ENCS_GROUPED NOT IN (' 1: 0', ' 2-3: 0', ' 4-5: 0', ' 6-7: 0', ' 8-9: 0', '10+: 0'	)
select * from #UTIL_TYPOL_SUMMIT_PATIENT where CNT_ED_IP_ENCS_GROUPED NOT IN (' 1: 0', ' 2-3: 0', ' 4-5: 0', ' 6-7: 0', ' 8-9: 0', '10+: 0'	)

--ABSMC SUMMIT CAMPUS TYPOLOGY
/*
select 
        cnt_ed_ip_encs_grouped,
		COUNT(*) as cnt_patients_summit
from #UTIL_TYPOL_SUMMIT_PATIENT
group by cnt_ed_ip_encs_grouped
ORDER BY cnt_ed_ip_encs_grouped

select * from #UTIL_TYPOL_SUMMIT_PATIENT where CNT_ED_IP_ENCS_GROUPED NOT IN (' 1: 0', ' 2-3: 0', ' 4-5: 0', ' 6-7: 0', ' 8-9: 0', '10+: 0'	)

 (*/

IF OBJECT_ID('tempdb..#UTIL_TYPOL_SUMMIT_PATIENT') IS NOT NULL DROP Table #UTIL_TYPOL_SUMMIT_PATIENT;
SELECT PAT_ID, 
	   CASE WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 1'   AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 0') THEN ' 1: 0'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 2-3' AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 0') THEN ' 2-3: 0'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 4-5' AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 0') THEN ' 4-5: 0'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 6-7' AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 0') THEN ' 6-7: 0'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 8-9' AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 0') THEN ' 8-9: 0'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = '10+'  AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 0') THEN '10+: 0'	
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 0'   AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 1') THEN ' 0: 1'	
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 1'   AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 1') THEN ' 1: 1'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 2-3' AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 1') THEN ' 2-3: 1'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 4-5' AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 1') THEN ' 4-5: 1'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 6-7' AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 1') THEN ' 6-7: 1'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 8-9' AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 1') THEN ' 8-9: 1'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = '10+'  AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 1') THEN '10+: 1'	
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 0'   AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 2') THEN ' 0: 2'	
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 1'   AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 2') THEN ' 1: 2'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 2-3' AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 2') THEN ' 2-3: 2'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 4-5' AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 2') THEN ' 4-5: 2'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 6-7' AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 2') THEN ' 6-7: 2'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 8-9' AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 2') THEN ' 8-9: 2'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = '10+'  AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 2') THEN '10+: 2'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 0'   AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 3-4') THEN ' 0: 3-4'	
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 1'   AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 3-4') THEN ' 1: 3-4'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 2-3' AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 3-4') THEN ' 2-3: 3-4'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 4-5' AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 3-4') THEN ' 4-5: 3-4'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 6-7' AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 3-4') THEN ' 6-7: 3-4'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 8-9' AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 3-4') THEN ' 8-9: 3-4'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = '10+'  AND CNT_IP_ADMITS_SUMMIT_GROUPED = ' 3-4') THEN '10+: 3-4'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 0'   AND CNT_IP_ADMITS_SUMMIT_GROUPED = '5+') THEN ' 0:5+'	
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 1'   AND CNT_IP_ADMITS_SUMMIT_GROUPED = '5+') THEN ' 1:5+'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 2-3' AND CNT_IP_ADMITS_SUMMIT_GROUPED = '5+') THEN ' 2-3:5+'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 4-5' AND CNT_IP_ADMITS_SUMMIT_GROUPED = '5+') THEN ' 4-5:5+'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 6-7' AND CNT_IP_ADMITS_SUMMIT_GROUPED = '5+') THEN ' 6-7:5+'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = ' 8-9' AND CNT_IP_ADMITS_SUMMIT_GROUPED = '5+') THEN ' 8-9:5+'
			WHEN (CNT_ED_VISITS_SUMMIT_GROUPED = '10+'  AND CNT_IP_ADMITS_SUMMIT_GROUPED = '5+') THEN '10+:5+'				
		END AS CNT_ED_IP_ENCS_GROUPED
	INTO #UTIL_TYPOL_SUMMIT_PATIENT    
	FROM (
		SELECT PAT_ID, 
		   CASE WHEN CNT_ED_VISITS_SUMMIT = 0 THEN ' 0'
				WHEN CNT_ED_VISITS_SUMMIT IS NULL THEN ' 0'
				WHEN CNT_ED_VISITS_SUMMIT = 1 THEN ' 1'
				WHEN CNT_ED_VISITS_SUMMIT BETWEEN 2 AND 3 THEN ' 2-3'
				WHEN CNT_ED_VISITS_SUMMIT BETWEEN 4 AND 5 THEN ' 4-5'
				WHEN CNT_ED_VISITS_SUMMIT BETWEEN 6 AND 7 THEN ' 6-7'
				WHEN CNT_ED_VISITS_SUMMIT BETWEEN 8 AND 9 THEN ' 8-9'
				WHEN CNT_ED_VISITS_SUMMIT >= 10 THEN '10+'
			END AS CNT_ED_VISITS_SUMMIT_GROUPED,
			CASE WHEN CNT_IP_ADMITS_SUMMIT = 0 THEN ' 0'
				WHEN CNT_IP_ADMITS_SUMMIT IS NULL THEN ' 0'
				WHEN CNT_IP_ADMITS_SUMMIT = 1 THEN ' 1'
				WHEN CNT_IP_ADMITS_SUMMIT = 2 THEN ' 2'
				WHEN CNT_IP_ADMITS_SUMMIT BETWEEN 3 AND 4 THEN ' 3-4'
				WHEN CNT_IP_ADMITS_SUMMIT >= 5 THEN '5+'
			END AS CNT_IP_ADMITS_SUMMIT_GROUPED
		FROM (
			SELECT 
			   CASE WHEN B.PAT_ID IS NULL THEN C.PAT_ID
					ELSE B.PAT_ID
					END AS PAT_ID,
				B.CNT_ED_VISITS_SUMMIT,
				C.CNT_IP_ADMITS_SUMMIT
			FROM (
					SELECT PAT_ID,
						   COUNT(*) AS CNT_ED_VISITS_SUMMIT
					FROM (
						SELECT * 
						FROM  #UTIL_TYPOL_ED_VISITS_2016
						WHERE LOC_NAME = 'ALTA BATES SUMMIT - MERRITT'
					) AS A
					GROUP BY A.PAT_ID
			) AS B

			FULL JOIN 

			(
					SELECT PAT_ID,
							COUNT(*) AS CNT_IP_ADMITS_SUMMIT
					FROM (
						SELECT * 
						FROM #UTIL_TYPOL_IP_ADMITS_2016
						WHERE LOC_NAME = 'ALTA BATES SUMMIT - MERRITT'
					     ) AS A
					GROUP BY A.PAT_ID
			) AS C
			ON B.PAT_ID = C.PAT_ID
		) AS D
	) AS E
/*) as f
group by f.cnt_ed_ip_encs_grouped*/




select * from #UTIL_TYPOL_ASHBY_PATIENTS where CNT_ED_IP_ENCS_GROUPED NOT IN (' 1: 0', ' 2-3: 0', ' 4-5: 0', ' 6-7: 0', ' 8-9: 0', '10+: 0'	)
select * from #UTIL_TYPOL_SUMMIT_PATIENT where CNT_ED_IP_ENCS_GROUPED NOT IN (' 1: 0', ' 2-3: 0', ' 4-5: 0', ' 6-7: 0', ' 8-9: 0', '10+: 0'	)



--Alta Bates: pull out pt with times of in pt. 
IF OBJECT_ID('tempdb..#UTIL_ASHBY_IP_SUMMARY_2016') IS NOT NULL DROP Table #UTIL_ASHBY_IP_SUMMARY_2016;
SELECT PAT_ID, 
			CASE WHEN CNT_IP_ADMITS_ASHBY = 0 THEN ' 0'
				WHEN CNT_IP_ADMITS_ASHBY IS NULL THEN ' 0'
				WHEN CNT_IP_ADMITS_ASHBY = 1 THEN ' 1'
				WHEN CNT_IP_ADMITS_ASHBY = 2 THEN ' 2'
				WHEN CNT_IP_ADMITS_ASHBY BETWEEN 3 AND 4 THEN ' 3-4'
				WHEN CNT_IP_ADMITS_ASHBY >= 5 THEN '5+'
			END AS CNT_IP_ADMITS_ASHBY_GROUPED
INTO #UTIL_ASHBY_IP_SUMMARY_2016
		FROM(
				SELECT PAT_ID
				, COUNT(*) AS CNT_IP_ADMITS_ASHBY
				FROM (
						SELECT * 
						FROM #UTIL_TYPOL_IP_ADMITS_2016
						WHERE LOC_NAME = 'ALTA BATES SUMMIT - ALTA BATES'
					) AS A
				GROUP BY A.PAT_ID
              ) AS B
ORDER BY CNT_IP_ADMITS_ASHBY_GROUPED

/*
--select * from #UTIL_ASHBY_IP_SUMMARY_2016 where CNT_IP_ADMITS_ASHBY_GROUPED = ' 3-4'

SELECT IPTOTAL.*
FROM #UTIL_TYPOL_IP_ADMITS_2016 AS IPTOTAL 
     INNER JOIN #UTIL_ASHBY_IP_SUMMARY_2016 AS ASHBY ON IPTOTAL.PAT_ID = ASHBY.PAT_ID
WHERE ASHBY.PAT_ID IS NOT NULL
     --AND ASHBY.CNT_IP_ADMITS_ASHBY_GROUPED = ' 1'
	 -- AND ASHBY.CNT_IP_ADMITS_ASHBY_GROUPED = ' 2'
	  AND ASHBY.CNT_IP_ADMITS_ASHBY_GROUPED = ' 3-4'

*/


--10/25/2016 use this
SELECT IPTOTAL.*, ASHBY.CNT_ED_IP_ENCS_GROUPED
FROM #UTIL_TYPOL_IP_ADMITS_2016 AS IPTOTAL 
     INNER JOIN (select * from #UTIL_TYPOL_ASHBY_PATIENTS where CNT_ED_IP_ENCS_GROUPED NOT IN (' 1: 0', ' 2-3: 0', ' 4-5: 0', ' 6-7: 0', ' 8-9: 0', '10+: 0'	)) AS ASHBY 
	 ON IPTOTAL.PAT_ID = ASHBY.PAT_ID
WHERE ASHBY.PAT_ID is not null LOC_NAME = 'ALTA BATES SUMMIT - ALTA BATES'












--***************************************************************************************

--Summit: pull out pt with times of in pt. 
IF OBJECT_ID('tempdb..#UTIL_SUMMIT_IP_SUMMARY_2016') IS NOT NULL DROP Table #UTIL_SUMMIT_IP_SUMMARY_2016;
SELECT PAT_ID, 
			CASE WHEN CNT_IP_ADMITS_SUMMIT = 0 THEN ' 0'
				WHEN CNT_IP_ADMITS_SUMMIT IS NULL THEN ' 0'
				WHEN CNT_IP_ADMITS_SUMMIT = 1 THEN ' 1'
				WHEN CNT_IP_ADMITS_SUMMIT = 2 THEN ' 2'
				WHEN CNT_IP_ADMITS_SUMMIT BETWEEN 3 AND 4 THEN ' 3-4'
				WHEN CNT_IP_ADMITS_SUMMIT >= 5 THEN '5+'
			END AS CNT_IP_ADMITS_SUMMIT_GROUPED
INTO #UTIL_SUMMIT_IP_SUMMARY_2016
		FROM(
               SELECT PAT_ID
                      , COUNT(*) AS CNT_IP_ADMITS_SUMMIT
               FROM (
		              SELECT * 
		              FROM #UTIL_TYPOL_IP_ADMITS_2016
		              WHERE LOC_NAME = 'ALTA BATES SUMMIT - MERRITT'
                    ) AS A
               GROUP BY A.PAT_ID
          ) AS B
ORDER BY CNT_IP_ADMITS_SUMMIT_GROUPED

--select count(*) from #UTIL_SUMMIT_IP_SUMMARY_2016 where CNT_IP_ADMITS_SUMMIT_GROUPED = '5+'


/*
SELECT IPTOTAL.*
FROM #UTIL_TYPOL_IP_ADMITS_2016 AS IPTOTAL 
     INNER JOIN #UTIL_SUMMIT_IP_SUMMARY_2016 AS SUMMIT ON IPTOTAL.PAT_ID = SUMMIT.PAT_ID
WHERE SUMMIT.PAT_ID IS NOT NULL
     --AND SUMMIT.CNT_IP_ADMITS_SUMMIT_GROUPED = ' 1'
	-- AND SUMMIT.CNT_IP_ADMITS_SUMMIT_GROUPED = ' 2'
	  AND SUMMIT.CNT_IP_ADMITS_SUMMIT_GROUPED = ' 3-4'
	-- AND SUMMIT.CNT_IP_ADMITS_SUMMIT_GROUPED = '5+'
*/


---10/25/2016 
SELECT IPTOTAL.*, SUMMIT.CNT_ED_IP_ENCS_GROUPED
FROM #UTIL_TYPOL_IP_ADMITS_2016 AS IPTOTAL 
     INNER JOIN (select * from #UTIL_TYPOL_SUMMIT_PATIENT where CNT_ED_IP_ENCS_GROUPED NOT IN (' 1: 0', ' 2-3: 0', ' 4-5: 0', ' 6-7: 0', ' 8-9: 0', '10+: 0'	)) AS SUMMIT
	 ON IPTOTAL.PAT_ID = SUMMIT.PAT_ID
WHERE SUMMIT.PAT_ID is not null 
      and IPTOTAL.LOC_NAME = 'ALTA BATES SUMMIT - MERRITT'























--********************************************************************************************----
--********************************************************************************************----
--PULL NAMES AND DEMOGRAPHICS
IF OBJECT_ID('tempdb..#ashby_names') IS NOT NULL DROP Table #ashby_names;
SELECT A.PAT_ID,
		B.PAT_MRN_ID,
		B.PAT_FIRST_NAME,
		B.PAT_MIDDLE_NAME,
		B.PAT_LAST_NAME,
		B.BIRTH_DATE,
		CASE WHEN B.SEX_C = '1' THEN 'FEMALE'
			WHEN B.SEX_C = '2' THEN 'MALE'
			WHEN B.SEX_C = '3' THEN 'UNKNOWN'
			ELSE 'UNKNOWN'
		END AS GENDER,
		D.NAME AS RACE,
		A.CNT_ED_IP_ENCS_GROUPED,
		ROW_NUMBER() OVER(PARTITION BY A.PAT_ID ORDER BY A.PAT_ID, C.PATIENT_RACE_C) AS RACE_I
INTO #ASHBY_NAMES		
FROM UTIL_TYPOL_ASHBY_PATIENTS AS A
INNER JOIN DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.PATIENT AS B
ON A.PAT_ID = B.PAT_ID
LEFT JOIN DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.PATIENT_RACE AS C
ON A.PAT_ID = C.PAT_ID
LEFT JOIN DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.ZC_PATIENT_RACE AS D
ON C.PATIENT_RACE_C = D.PATIENT_RACE_C
WHERE A.CNT_ED_IP_ENCS_GROUPED IN (' 4-5: 0', ' 6-7: 0', ' 8-9: 0', '10+: 0', '10+:5+')







IF OBJECT_ID('tempdb..#ashby_names') IS NOT NULL DROP Table #ashby_names;
DROP TABLE UTIL_TYPOL_ASHBY_PATIENTS_NAMES
DECLARE @COLS AS NVARCHAR(MAX), @QUERY AS NVARCHAR(MAX)
SELECT @COLS = STUFF((SELECT ',' + QUOTENAME(RACE_I) 
                    FROM #ASHBY_NAMES
                    GROUP BY RACE_I
                    ORDER BY RACE_I 
                    FOR XML PATH(''), TYPE).VALUE('.', 'NVARCHAR(MAX)'),1,1,'')  
SET @QUERY = 'SELECT PAT_ID, PAT_MRN_ID, PAT_FIRST_NAME, PAT_MIDDLE_NAME, PAT_LAST_NAME, BIRTH_DATE, GENDER, CNT_ED_IP_ENCS_GROUPED, ' + @COLS + '
			INTO UTIL_TYPOL_ASHBY_PATIENTS_NAMES
			FROM (
			SELECT *
			FROM #ASHBY_NAMES
            ) X
			PIVOT 
            (
            MAX(RACE)
			FOR RACE_I IN (' + @COLS + ')
            ) P'
EXECUTE(@QUERY);

SELECT * FROM UTIL_TYPOL_ASHBY_PATIENTS_NAMES








IF OBJECT_ID('tempdb..#SUMMIT_NAMES') IS NOT NULL DROP Table #SUMMIT_NAMES;
SELECT A.PAT_ID,
		B.PAT_MRN_ID,
		B.PAT_FIRST_NAME,
		B.PAT_MIDDLE_NAME,
		B.PAT_LAST_NAME,
		B.BIRTH_DATE,
		CASE WHEN B.SEX_C = '1' THEN 'FEMALE'
			WHEN B.SEX_C = '2' THEN 'MALE'
			WHEN B.SEX_C = '3' THEN 'UNKNOWN'
			ELSE 'UNKNOWN'
		END AS GENDER,
		D.NAME AS RACE,
		A.CNT_ED_IP_ENCS_GROUPED,
		ROW_NUMBER() OVER(PARTITION BY A.PAT_ID ORDER BY A.PAT_ID, C.PATIENT_RACE_C) AS RACE_I
INTO #SUMMIT_NAMES	
FROM #UTIL_TYPOL_SUMMIT_PATIENTS AS A
     INNER JOIN DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.PATIENT AS B ON A.PAT_ID = B.PAT_ID
     LEFT JOIN DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.PATIENT_RACE AS C ON A.PAT_ID = C.PAT_ID
     LEFT JOIN DCPWDBS149.CLARITY_RPT_CRYSTAL.DBO.ZC_PATIENT_RACE AS D ON C.PATIENT_RACE_C = D.PATIENT_RACE_C
WHERE A.CNT_ED_IP_ENCS_GROUPED IN (' 4-5: 0', ' 6-7: 0', ' 8-9: 0', '10+: 0', '10+:5+')









IF OBJECT_ID(N'GIS.DBO.UTIL_TYPOL_SUMMIT_PATIENTS_NAMESS', N'U') IS NOT NULL
DROP TABLE UTIL_TYPOL_SUMMIT_PATIENTS_NAMES
DECLARE @COLS AS NVARCHAR(MAX), @QUERY AS NVARCHAR(MAX)
SELECT @COLS = STUFF((SELECT ',' + QUOTENAME(RACE_I) 
                    FROM #SUMMIT_NAMES
                    GROUP BY RACE_I
                    ORDER BY RACE_I 
                    FOR XML PATH(''), TYPE).VALUE('.', 'NVARCHAR(MAX)'),1,1,'')  
SET @QUERY = 'SELECT PAT_ID, PAT_MRN_ID, PAT_FIRST_NAME, PAT_MIDDLE_NAME, PAT_LAST_NAME, BIRTH_DATE, GENDER, CNT_ED_IP_ENCS_GROUPED, ' + @COLS + '
			INTO UTIL_TYPOL_SUMMIT_PATIENTS_NAMES
			FROM (
			SELECT *
			FROM #SUMMIT_NAMES
            ) X
			PIVOT 
            (
            MAX(RACE)
			FOR RACE_I IN (' + @COLS + ')
            ) P'
EXECUTE(@QUERY);
							
SELECT * FROM UTIL_TYPOL_SUMMIT_PATIENTS_NAMES